apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: devops-case-app-scaledobject
spec:
  scaleTargetRef:
    name: devops-case-app
  minReplicaCount: 1
  maxReplicaCount: 10
  cooldownPeriod: 30
  pollingInterval: 5
  triggers:
  - type: cpu
    metadata:
      type: Utilization
      value: "50"  
  - type: memory
    metadata:
      type: Utilization
      value: "60"  