name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  

env:
  DOCKER_IMAGE: bthngcr/devops-case-app
  DOCKER_TAG: latest

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies 
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt
        pip install "Flask==2.1.0" 

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./app
        push: ${{ github.ref == 'refs/heads/main' }}
        tags: ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}